language: node_js
node_js:
  - "7"

services:
  - docker

cache:
  directories:
    - "node_modules"
before_script:
  - npm install mocha -g

script:
  - cd thedoctor && npm test



after_success:
  - cd $TRAVIS_BUILD_DIR/thedoctor && docker build -t lxndrv/thedoctor .
  - docker images
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD";
    docker push lxndrv/thedoctor;
    fi
